version: "3.7"
services:
  db:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 54321:5432
  backend:
    build: backend
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/usr/src/backend-app
      - ./backend/tmp/bundle_cache:/usr/src/bundle_cache
    ports:
      - "3002:3000"
    env_file:
      - .env
  frontend:
    build: frontend
    ports:
      - "3003:3000"
      - "9229:9229"
    stdin_open: true
    volumes:
      # - node_modules:/usr/src/frontend-app/node_modules
      - ./frontend:/usr/src/frontend-app
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'

volumes:
  bundle_cache:
  node_modules:
  db_data:
