version: "3.7"
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 54321:5432
  backend:
    build: backend
    command: bundle exec rails s
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/backend-app
    ports:
      - 3002:3000
    env_file:
      - .env
