version: "3.7"
services:
  db:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 54321:5432
  backend:
    build: backend
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/backend-app
      - ./backend/tmp/bundle_cache:/usr/src/bundle_cache
    ports:
      - "3002:3000"
    env_file:
      - .env

volumes:
  bundle_cache:
  node_modules:
  db_data:
